name: Matrix

on:
  workflow_dispatch:
  
jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest

    strategy:
      matrix:
        platform: [win32, linux, darwin]
        arch: [ia32, x64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm ci

      - name: Build add-on
        run: npm run build --target_arch=${{ matrix.arch }} --target_platform=${{ matrix.platform }}

      - name: Archive build
        uses: actions/upload-artifact@v2
        with:
          name: addon-${{ matrix.platform }}-${{ matrix.arch }}
          path: build/Release
